// <auto-generated />
using System;
using ContaBancaria.Autorizacoes.Api.Infraestrutura.BancoDeDados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContaBancaria.Autorizacoes.Api.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210901224856_BaseAutorizacao")]
    partial class BaseAutorizacao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.ClienteCredenciais", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAtivo");

                    b.Property<string>("Senha");

                    b.Property<string>("Usuario");

                    b.HasKey("Id");

                    b.ToTable("Credenciais");
                });

            modelBuilder.Entity("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.Dispositivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Chave");

                    b.Property<bool>("IsAtivo");

                    b.HasKey("Id");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.Sessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao");

                    b.Property<long?>("DispositivoId");

                    b.Property<bool>("IsAtivo");

                    b.Property<bool>("IsNotValido");

                    b.Property<Guid>("Token");

                    b.HasKey("Id");

                    b.HasIndex("DispositivoId");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ClienteCredenciaisId");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<bool>("IsAtivo");

                    b.Property<bool>("IsNotValido");

                    b.Property<Guid?>("SessaoId");

                    b.Property<Guid>("Token");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCredenciaisId");

                    b.HasIndex("SessaoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.Sessao", b =>
                {
                    b.HasOne("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.Dispositivo", "Dispositivo")
                        .WithMany()
                        .HasForeignKey("DispositivoId");
                });

            modelBuilder.Entity("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.Transacao", b =>
                {
                    b.HasOne("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.ClienteCredenciais", "ClienteCredenciais")
                        .WithMany()
                        .HasForeignKey("ClienteCredenciaisId");

                    b.HasOne("ContaBancaria.Autorizacoes.Api.Negocio.Modelos.Sessao", "Sessao")
                        .WithMany()
                        .HasForeignKey("SessaoId");
                });
#pragma warning restore 612, 618
        }
    }
}
